#!/usr/bin/env node

import * as GeoRSSToGeoJSON from './GeoRSSToGeoJSON.js'
import fs from 'node:fs'
import { DOMParser } from '@xmldom/xmldom'

const args = process.argv.slice(2)
if (args.length !== 1) {
  console.log('Usage: ./georsstogeojson $file')
  process.exit(1)
}

process.stdout.write(
  JSON.stringify(
    GeoRSSToGeoJSON.parse(
      new DOMParser().parseFromString(fs.readFileSync(args[0], 'utf8'), 'text/xml')
    )
  )
)
