#!/usr/bin/env node

const t = require('./GeoRSSToGeoJSON').GeoRSSToGeoJSON
const args = process.argv.slice(2)
const fs = require('node:fs')
const { DOMParser } = require('@xmldom/xmldom')
if (args.length !== 1) {
  console.log('Usage: ./georsstogeojson $file')
  process.exit(1)
}

process.stdout.write(
  JSON.stringify(
    t(new DOMParser().parseFromString(fs.readFileSync(args[0], 'utf8'), 'text/xml'))
  )
)
